# VERSAT@lcc (IST: gcrs 2019)
# R12 = SP; R11 = FP
	ldi 1
	wrw R12
	ldi ADDR_W
	addi -1
	wrw RB
_next	rdw RB
	beqi _top
	rdw R12
	shft -1
	wrw R12
	rdw RB
	addi -1
	wrw RB
	ldi 0
	beqi _next
_top	rdw R12
	addi -1
	addi MEM_BASE
	wrw R12
	wrw RB
	ldi end
	wrwb
	ldi 0
	wrw R11 #FP=0
	beqi main
	nop
end	ldi 0xF
	and R1
	addi 0x30
	wrw CPRT_BASE
	ldi 0xa
	wrw CPRT_BASE
	ldi 1
	wrw R12
	ldi ADDR_W
	wrw RB
_again	rdw RB
	beqi _trap
	rdw R12
	shft -1
	wrw R12
	rdw RB
	addi -1
	wrw RB
	ldi 0
	beqi _again
_trap	rdw R12
	addi -1
	addi MEM_BASE
	wrw RB
	wrwb
# DATA
# global loopAddr
loopAddr	.memset 604
# global pushAddr
pushAddr	.memset 602
# global debouce
# TEXT
# debouce ncalls=0 nargs=1 used=38
debouce	nop
# PUSH r3
	rdw R12
	addi -1
	wrw R12
	wrw RB
	rdw R3
	wrwb
# PUSH r4
	rdw R12
	addi -1
	wrw R12
	wrw RB
	rdw R4
	wrwb
# PUSH r5
	rdw R12
	addi -1
	wrw R12
	wrw RB
	rdw R5
	wrwb
# save fp: PUSH fp; MOV fp, sp
	rdw R12
	addi -1
	wrw R12
	wrw RB
	rdw R11
	wrwb
	rdw R12
	wrw R11
# debouce {begin} framesize=0 nofp=0
 # ADDRGP1
	ldi debouncevar
	wrw R5
 # INDIRI1(fpN)
	rdw R11
	addi 5
	wrw RB
	rdwb
	rdwb
	wrw R4
 # ASGNI1(addrg,reg)
	rdw R5
	wrw RB
	rdw R4
	wrwb
 # LABELV
L2	nop
 # LABELV
L3	nop
 # ADDRGP1
	ldi debouncevar
	wrw R5
## ASGN=1079 ##
## INDIR=1095 ##
 # reg: INDIRI1(reg)
	rdw R5
	wrw RB
	rdwb
	rdwb
	wrw R4
## ASGN=1077 ##
## INDIR=1095 ##
## INDIR=1093 ##
 # reg: con
	ldi 1
	wrw R3
 # SUBI1(reg,reg)
	rdw R4
	sub R3
	wrw R3
 # ASGNI1(addr,reg)
	rdw R5
	wrw RB
	rdw R3
	wrwb
## INDIR=1093 ##
 # reg: con
	ldi 0
	wrw R5
 # NEI1
	rdw R4
	sub R5
	bneqi L2
	nop
 # LABELV
L1	nop
# debouce {end}
# restore fp: MOV sp, fp; POP fp
	rdw R11
	wrw R12
	wrw RB
	rdwb
	rdwb
	wrw R11
	rdw R12
	addi 1
	wrw R12
# POP r5
	rdw R12
	wrw RB
	rdwb
	rdwb
	wrw R5
	rdw R12
	addi 1
	wrw R12
# POP r4
	rdw R12
	wrw RB
	rdwb
	rdwb
	wrw R4
	rdw R12
	addi 1
	wrw R12
# POP r3
	rdw R12
	wrw RB
	rdwb
	rdwb
	wrw R3
	rdw R12
	addi 1
	wrw R12
# RET
	rdw R12
	wrw RB
	rdwb
	rdwb
	wrw RB
	rdw R12
	addi 1
	wrw R12
	ldi 0
	beq RB
	nop

# global main
# main ncalls=1 nargs=0 used=7e2
main	nop
# PUSH r5
	rdw R12
	addi -1
	wrw R12
	wrw RB
	rdw R5
	wrwb
# PUSH r6
	rdw R12
	addi -1
	wrw R12
	wrw RB
	rdw R6
	wrwb
# PUSH r7
	rdw R12
	addi -1
	wrw R12
	wrw RB
	rdw R7
	wrwb
# PUSH r8
	rdw R12
	addi -1
	wrw R12
	wrw RB
	rdw R8
	wrwb
# PUSH r9
	rdw R12
	addi -1
	wrw R12
	wrw RB
	rdw R9
	wrwb
# PUSH r10
	rdw R12
	addi -1
	wrw R12
	wrw RB
	rdw R10
	wrwb
# main {begin} framesize=0 nofp=1
 # ADDRGP1
	ldi loopAddr
	wrw R5
 # INDIRI1(addrg)
	rdw R5
	wrw RB
	rdwb
	rdwb
	wrw R5
 # LOADP1(reg)
	rdw R5
	wrw R6
## ASGN=1079 ##
 # ADDRGP1
	ldi pushAddr
	wrw R5
 # INDIRI1(addrg)
	rdw R5
	wrw RB
	rdwb
	rdwb
	wrw R5
 # LOADP1(reg)
	rdw R5
	wrw R7
## ASGN=1079 ##
 # reg: con
	ldi 0
	wrw R10
## ASGN=1077 ##
 # reg: con
	ldi 0
	wrw R8
## ASGN=1077 ##
 # reg: con
	ldi 0
	wrw R9
## ASGN=1077 ##
## INDIR=1095 ##
 # ASGNI1(addr,con)
	rdw R6
	wrw RB
	ldi 0
	wrwb
 # JUMPV(addrj)
	ldi 0
	beqi L7
	nop
 # LABELV
L6	nop
## INDIR=1095 ##
 # reg: INDIRI1(reg)
	rdw R7
	wrw RB
	rdwb
	rdwb
	wrw R9
## ASGN=1077 ##
## INDIR=1093 ##
 # reg: con
	ldi 2
	wrw R5
 # NEI1
	rdw R9
	sub R5
	bneqi L9
	nop
## INDIR=1093 ##
 # reg: con
	ldi 7
	wrw R5
 # NEI1
	rdw R10
	sub R5
	bneqi L11
	nop
## INDIR=1093 ##
 # LOADI1(reg)
	rdw R8
	wrw R10
## ASGN=1077 ##
 # JUMPV(addrj)
	ldi 0
	beqi L10
	nop
 # LABELV
L11	nop
## INDIR=1093 ##
 # ADDI1(reg,con)
	rdw R8
	addi 1
	wrw R10
## ASGN=1077 ##
 # JUMPV(addrj)
	ldi 0
	beqi L10
	nop
 # LABELV
L9	nop
## INDIR=1093 ##
 # reg: con
	ldi 1
	wrw R5
 # NEI1
	rdw R9
	sub R5
	bneqi L13
	nop
## INDIR=1093 ##
 # reg: con
	ldi 0
	wrw R5
 # NEI1
	rdw R10
	sub R5
	bneqi L15
	nop
## INDIR=1093 ##
 # LOADI1(reg)
	rdw R8
	wrw R10
## ASGN=1077 ##
 # JUMPV(addrj)
	ldi 0
	beqi L14
	nop
 # LABELV
L15	nop
## INDIR=1093 ##
 # reg: con
	ldi 1
	wrw R5
 # SUBI1(reg,reg)
	rdw R8
	sub R5
	wrw R10
## ASGN=1077 ##
 # JUMPV(addrj)
	ldi 0
	beqi L14
	nop
 # LABELV
L13	nop
## INDIR=1093 ##
 # reg: con
	ldi 5
	wrw R5
 # NEI1
	rdw R9
	sub R5
	bneqi L17
	nop
 # reg: con
	ldi 7
	wrw R10
## ASGN=1077 ##
 # JUMPV(addrj)
	ldi 0
	beqi L18
	nop
 # LABELV
L17	nop
## INDIR=1093 ##
 # reg: con
	ldi 4
	wrw R5
 # NEI1
	rdw R9
	sub R5
	bneqi L19
	nop
 # reg: con
	ldi 0
	wrw R10
## ASGN=1077 ##
 # LABELV
L19	nop
 # LABELV
L18	nop
 # LABELV
L14	nop
 # LABELV
L10	nop
## INDIR=1093 ##
## INDIR=1093 ##
 # EQI1
	rdw R8
	sub R10
	beqi L21
	nop
## INDIR=1095 ##
## INDIR=1093 ##
 # ASGNI1(addr,reg)
	rdw R6
	wrw RB
	rdw R10
	wrwb
## INDIR=1093 ##
 # LOADI1(reg)
	rdw R10
	wrw R8
## ASGN=1077 ##
 # LABELV
L21	nop
 # ARGI1(con)
	rdw R12
	addi -1
	wrw R12
	wrw RB
	ldi 393216
	wrwb
# CALL
	rdw R12
	addi -1
	wrw R12
	wrw RB
	ldi L26
	wrwb
	ldi 0
	beqi debouce
L26	nop
	rdw R12
	addi 1
	wrw R12
 # LABELV
L7	nop
 # JUMPV(addrj)
	ldi 0
	beqi L6
	nop
 # LABELV
L23	nop
 # LABELV
L24	nop
 # JUMPV(addrj)
	ldi 0
	beqi L23
	nop
 # reg: con
	ldi 0
	wrw R1
## RET=1269 ##
 # LABELV
L5	nop
# main {end}
# POP r10
	rdw R12
	wrw RB
	rdwb
	rdwb
	wrw R10
	rdw R12
	addi 1
	wrw R12
# POP r9
	rdw R12
	wrw RB
	rdwb
	rdwb
	wrw R9
	rdw R12
	addi 1
	wrw R12
# POP r8
	rdw R12
	wrw RB
	rdwb
	rdwb
	wrw R8
	rdw R12
	addi 1
	wrw R12
# POP r7
	rdw R12
	wrw RB
	rdwb
	rdwb
	wrw R7
	rdw R12
	addi 1
	wrw R12
# POP r6
	rdw R12
	wrw RB
	rdwb
	rdwb
	wrw R6
	rdw R12
	addi 1
	wrw R12
# POP r5
	rdw R12
	wrw RB
	rdwb
	rdwb
	wrw R5
	rdw R12
	addi 1
	wrw R12
# RET
	rdw R12
	wrw RB
	rdwb
	rdwb
	wrw RB
	rdw R12
	addi 1
	wrw R12
	ldi 0
	beq RB
	nop

# BSS
# global debouncevar
debouncevar	.memset 0x00
_end	.memset 0
### The end ###
