# 
# Hello World!
#
#	a simple picoVersat program
#

# uncomment test ADD instruction        
#        ldi 2
#        wrw R1
#        ldi 3
#        wrw R2
#        add R1
#        wrw TRAP_BASE


# set R1 iterator 	
#	ldi 15
#	wrw R1
	
# set RB to point to first char
#        ldi c0
#        wrw R4
#	wrw RB

# read string from memory and write to char printer 
# loop 	rdwb
#	rdwb            #need to read twice due to memory 1 cycle delay
#	wrw CPRT_BASE
#	rdw RB          #load pointer
#	addi 1	        #increment by 1
#	wrw RB          #store incremented pointer
#	rdw R1          #load iterator
#	bneqi loop      #go back to loop if non-zero, regA is decremented
#	wrw R1          #stores back decremented iterator

op1	.memset 0x03
op2 .memset 0x02

# R1 - OP1
# R2 - OP2
# R3 iteration counter
# R4 result accumulator

ldi op1
wrw R1

ldi op2
wrw R2

ldi 0x00
wrw R3

ldi 0x00
wrw R4


loop # main loop



	ldi R3 # iterate and save iteration counter	
	add 0x01
	wrw R3

final # final print 
	
	wrw CPRT_BASE


#finish by activating trap
end	wrw TRAP_BASE
        
# char ascii constants placed here	
op1	.memset 0x03
op2 .memset 0x02